# Generated by Django 4.1.7 on 2023-03-30 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0001_initial'),
        ('mtihani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.qcategory'),
        ),
    ]
