# Generated by Django 4.1.7 on 2023-04-01 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0004_questionchoice_category'),
        ('mtihani', '0003_remove_exam_category_exam_questionchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.qcategory'),
        ),
    ]
