# Generated by Django 4.1.7 on 2023-04-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtihani', '0005_alter_exam_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='category',
            new_name='choice',
        ),
    ]
