# Generated by Django 4.1.7 on 2023-04-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtihani', '0006_rename_category_exam_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='choice',
        ),
    ]
