# Generated by Django 4.1.7 on 2023-04-01 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0003_questionainazote'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.qcategory'),
        ),
    ]
