# Generated by Django 4.1.7 on 2023-04-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtihani', '0007_remove_exam_choice'),
        ('FYPAPP', '0004_questionchoice_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionShortterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='qcategory',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questionchoice'),
        ),
        migrations.DeleteModel(
            name='QuestionAinazote',
        ),
        migrations.AddField(
            model_name='qcategory',
            name='short',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questionshortterm'),
        ),
    ]
