# Generated by Django 4.1.7 on 2023-04-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0005_questionshortterm_qcategory_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAinazote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questionchoice')),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questionshortterm')),
            ],
        ),
    ]
