# Generated by Django 4.1.7 on 2023-04-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0006_questionainazote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcategory',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='qcategory',
            name='short',
        ),
        migrations.AddField(
            model_name='questionshortterm',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.qcategory'),
        ),
        migrations.DeleteModel(
            name='QuestionAinazote',
        ),
    ]
