# Generated by Django 4.1.7 on 2023-04-05 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0007_remove_qcategory_choice_remove_qcategory_short_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLongTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.qcategory')),
            ],
        ),
    ]
